/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
	const { nodes, materials } = useGLTF("models/room.glb");
	return (
		<group {...props} dispose={null}>
			<group position={[2.097, 0.914, -1.474]}>
				<group
					position={[0.004, 0.543, -1.539]}
					rotation={[0, -1.08, 0]}
					scale={1.37}
				>
					<mesh
						geometry={nodes.FlowerPot4_1.geometry}
						material={materials.VaseFlowerPot4}
					/>
					<mesh
						geometry={nodes.FlowerPot4_2.geometry}
						material={materials.GroundFlowerPot4}
					/>
					<mesh
						geometry={nodes.FlowerPot4_3.geometry}
						material={materials.PlantFlowerPot4}
					/>
				</group>
			</group>
			<group position={[-3.712, 3.298, -3.743]} scale={0.451}>
				<group position={[1.812, 1.242, -0.076]} scale={1.416}>
					<mesh
						geometry={nodes.FlowerPot2_1.geometry}
						material={materials.ChainFlowerPot2}
					/>
					<mesh
						geometry={nodes.FlowerPot2_2.geometry}
						material={materials.VaseFlowerPot2}
					/>
					<mesh
						geometry={nodes.FlowerPot2_3.geometry}
						material={materials.GroundFlowerPot2}
					/>
					<mesh
						geometry={nodes.FlowerPot2_4.geometry}
						material={materials.LeafsFlowerPot2}
					/>
				</group>
			</group>
			<mesh
				geometry={nodes.Rug.geometry}
				material={materials.Mat}
				position={[-0.855, 0.025, -1.322]}
				scale={0.021}
			/>
			<group
				position={[-2.844, 1.926, -2.819]}
				rotation={[0, 0.653, 0]}
				scale={0.03}
			>
				<mesh
					geometry={nodes["Node-Mesh001"].geometry}
					material={materials.lambert4SG}
				/>
				<mesh
					geometry={nodes["Node-Mesh001_1"].geometry}
					material={materials.lambert2SG}
				/>
				<mesh
					geometry={nodes["Node-Mesh001_2"].geometry}
					material={materials.lambert3SG}
				/>
			</group>
			<group position={[0, 1.802, 1.007]}>
				<group
					position={[0.98, 1.439, -4.828]}
					rotation={[-Math.PI / 2, 0, 3.073]}
					scale={[18.103, 14.978, 14.962]}
				>
					<mesh
						geometry={nodes.DrumSet1_1.geometry}
						material={materials.Metal1DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_2.geometry}
						material={materials.Wood1DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_3.geometry}
						material={materials.Wood3DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_4.geometry}
						material={materials.Steel1DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_5.geometry}
						material={materials.Leather1DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_6.geometry}
						material={materials.Wood2DrumSet1}
					/>
					<mesh
						geometry={nodes.DrumSet1_7.geometry}
						material={materials["Material.016"]}
					/>
					<mesh
						geometry={nodes.DrumSet1_8.geometry}
						material={materials["Material.015"]}
					/>
					<mesh
						geometry={nodes.DrumSet1_9.geometry}
						material={materials.None}
					/>
					<mesh
						geometry={nodes.DrumSet1_10.geometry}
						material={materials["Material.007"]}
					/>
				</group>
			</group>
			<mesh
				geometry={nodes.coffeeMug.geometry}
				material={materials["lambert3SG.001"]}
				position={[0.627, 1.995, -2.89]}
				rotation={[0, -0.868, 0]}
				scale={0.01}
			/>
			<group
				position={[-1.199, 2.053, -3.031]}
				rotation={[-1.571, 0, 0.009]}
				scale={33.21}
			>
				<mesh
					geometry={nodes["Keyboard001|group1030983910|Dupli|22001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1075691498|Dupli|58001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1149852049|Dupli|53001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1152190519|Dupli|19001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1180881246|Dupli|50001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1238060299|Dupli|28001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1238428394|Dupli|61001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1272091893|Dupli|35001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1316349499|Dupli|39001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1323238240|Dupli|32001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group145618305|Dupli|23001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1486350934|Dupli|63001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group150579309|Dupli|11001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1529968652|Dupli|6001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1571332333|Dupli|33001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1581414308|Dupli|8001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1589752359|Dupli|26001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1629393722|Dupli|64001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1629609685|Dupli|21001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1675960081|Dupli|12001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1740918352|Dupli|46001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1753917514|Dupli|5001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1754683637|Dupli|40001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1764140354|Dupli|60001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1870575723|Dupli|65001"].geometry}
					material={materials["mat16.006"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1899843208|Dupli|36001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1956214489|Dupli|14001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group196400395|Dupli|15001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group1976194690|Dupli|18001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group205302596|Dupli|31001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group2074153597|Dupli|20001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group2085389804|Dupli|57001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group2091112366|Dupli|59001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group2106755496|Dupli|4001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group2146178072|Dupli|38001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group252681800|Dupli|7001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group268332703|Dupli|44001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group287159489|Dupli|13001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group295085766|Dupli|9001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group311988427|Dupli|1001"].geometry}
					material={materials["mat22.011"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group34220672|Dupli|34001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group384612072|Dupli|10001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group418912012|Dupli|30001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group42243725|Dupli|37001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group425587018|Dupli|001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group449779970|Dupli|3001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group45382983|Dupli|52001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group475225180|Dupli|41001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group573547017|Dupli|49001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group588539140|Dupli|47001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group601803475|Dupli|25001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group616518658|Dupli|56001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group687259746|Dupli|51001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group706802639|Dupli|17001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group729811280|Dupli|48001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group77921105|Dupli|42001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group790925258|Dupli|54001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group801095923|Dupli|29001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group806343109|Dupli|27001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group826580911|Dupli|24001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group873458270|Dupli|55001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group873558583|Dupli|62001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group877249531|Dupli|66001"].geometry}
					material={materials["mat9.002"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group954813675|Dupli|16001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<group
					position={[0.007, -0.003, -0.004]}
					rotation={[0, 0, 0.009]}
					scale={1.159}
				>
					<mesh
						geometry={nodes["Keyboard001|group96314515|Dupli|2001_1"].geometry}
						material={materials["mat21.013"]}
					/>
					<mesh
						geometry={nodes["Keyboard001|group96314515|Dupli|2001_2"].geometry}
						material={materials["mat22.011"]}
					/>
					<mesh
						geometry={nodes["Keyboard001|group96314515|Dupli|2001_3"].geometry}
						material={materials["mat16.006"]}
					/>
					<mesh
						geometry={nodes["Keyboard001|group96314515|Dupli|2001_4"].geometry}
						material={materials["mat9.002"]}
					/>
				</group>
				<mesh
					geometry={nodes["Keyboard001|group96968687|Dupli|43001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
				<mesh
					geometry={nodes["Keyboard001|group993315105|Dupli|45001"].geometry}
					material={materials["mat21.013"]}
					position={[0.035, -0.092, -0.062]}
					rotation={[1.571, -0.009, 0]}
					scale={0.03}
				/>
			</group>
			<group
				position={[-1.916, 1.938, -2.901]}
				rotation={[-Math.PI / 2, 0, 1.447]}
				scale={302.152}
			>
				<mesh
					geometry={nodes.Paper001_1.geometry}
					material={materials["mat21.001"]}
				/>
				<mesh
					geometry={nodes.Paper001_2.geometry}
					material={materials["mat15.001"]}
				/>
			</group>
			<mesh
				geometry={nodes.Mousepad001.geometry}
				material={materials.Mousepad}
				position={[-0.14, 1.918, -2.97]}
				rotation={[-Math.PI / 2, 0, 1.534]}
				scale={[17.231, 20.977, 0.228]}
			/>
			<group
				position={[0.742, 2.156, -3.231]}
				rotation={[-Math.PI / 2, 0, 1.662]}
				scale={[8561.475, 8561.475, 8561.471]}
			>
				<mesh
					geometry={nodes.Light_Desk002_1.geometry}
					material={materials["Black.097"]}
				/>
				<mesh
					geometry={nodes.Light_Desk002_2.geometry}
					material={materials["LightMetal.027"]}
				/>
				<mesh
					geometry={nodes.Light_Desk002_3.geometry}
					material={materials["White.053"]}
				/>
			</group>
			<mesh
				geometry={nodes.Mouse002.geometry}
				material={materials["Material.017"]}
				position={[-0.183, 1.923, -2.946]}
				rotation={[-Math.PI / 2, 0, 0.235]}
				scale={17771.596}
			/>
			<group
				position={[-0.834, 1.086, -1.805]}
				rotation={[1.57, -0.026, 3.128]}
				scale={-4.826}
			>
				<mesh
					geometry={nodes.Chair002_1.geometry}
					material={materials["Executive.002"]}
				/>
				<mesh
					geometry={nodes.Chair002_2.geometry}
					material={materials["Executive__1.002"]}
				/>
				<mesh
					geometry={nodes.Chair002_3.geometry}
					material={materials["Executive__2.002"]}
				/>
				<mesh
					geometry={nodes.Chair002_4.geometry}
					material={materials["Executive__3.002"]}
				/>
			</group>
			<group position={[6.427, 0.576, -1.609]}>
				<group
					position={[-2.732, 0.913, -5.184]}
					rotation={[-Math.PI / 2, 0, 3.105]}
					scale={1.135}
				>
					<group
						position={[3.55, 2.855, 0.363]}
						rotation={[0, 0, 1.523]}
						scale={[1.33, 2.072, 1.641]}
					>
						<mesh
							geometry={nodes["Monitor001|iMac|Dupli|004"].geometry}
							material={materials["Material.006"]}
						/>
						<mesh
							geometry={nodes["Monitor001|iMac|Dupli|004_1"].geometry}
							material={materials["Material.018"]}
						/>
					</group>
					<group
						position={[4.784, 3.092, 0.363]}
						rotation={[0, 0, 1.996]}
						scale={[1.33, 2.072, 1.641]}
					>
						<mesh
							geometry={nodes["Monitor001|iMac|Dupli|005"].geometry}
							material={materials["Material.020"]}
						/>
						<mesh
							geometry={nodes["Monitor001|iMac|Dupli|005_1"].geometry}
							material={materials["Material.021"]}
						/>
					</group>
				</group>
			</group>
			<mesh
				geometry={nodes.Cube002.geometry}
				material={materials["Material.022"]}
				position={[2.302, 3.784, -3.93]}
				scale={[0.742, 1.172, 0.043]}
			/>
			<group
				position={[0.248, 1.916, -3.018]}
				rotation={[1.601, 0.004, 3.095]}
				scale={0.172}
			>
				<mesh
					geometry={nodes.mesh15167646.geometry}
					material={materials["mat23.001"]}
				/>
				<mesh
					geometry={nodes.mesh15167646_1.geometry}
					material={materials.mat16}
				/>
				<mesh
					geometry={nodes.mesh15167646_2.geometry}
					material={materials["mat17.001"]}
				/>
				<mesh
					geometry={nodes.mesh15167646_3.geometry}
					material={materials.mat8}
				/>
				<mesh
					geometry={nodes.mesh15167646_4.geometry}
					material={materials["mat24.002"]}
				/>
				<mesh
					geometry={nodes.mesh15167646_5.geometry}
					material={materials["mat25.001"]}
				/>
				<mesh
					geometry={nodes.mesh15167646_6.geometry}
					material={materials.mat5}
				/>
				<mesh
					geometry={nodes.mesh15167646_7.geometry}
					material={materials.mat15}
				/>
			</group>
			<group
				position={[-1.199, 3.882, -3.91]}
				rotation={[0, -1.55, 0]}
				scale={1.308}
			>
				<mesh
					geometry={nodes["Node-Mesh004"].geometry}
					material={materials["mat23.003"]}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_1"].geometry}
					material={materials.mat18}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_2"].geometry}
					material={materials.mat12}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_3"].geometry}
					material={materials.mat3}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_4"].geometry}
					material={materials["mat8.002"]}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_5"].geometry}
					material={materials["mat15.005"]}
				/>
				<mesh
					geometry={nodes["Node-Mesh004_6"].geometry}
					material={materials["mat21.002"]}
				/>
			</group>
			<mesh
				geometry={nodes.Wall___Desk_Speaker001.geometry}
				material={materials["Mat.004"]}
				position={[0.634, 1.917, -3.489]}
				rotation={[Math.PI, -0.939, Math.PI]}
				scale={0.01}
			/>
			<mesh
				geometry={nodes.Wall___Desk_Speaker002.geometry}
				material={materials["Mat.004"]}
				position={[-2.504, 1.905, -3.262]}
				rotation={[0, -0.632, 0]}
				scale={0.01}
			/>
			<group
				position={[-0.308, 0.225, -0.093]}
				rotation={[Math.PI, -1.565, Math.PI]}
				scale={[0.816, 1, 0.822]}
			>
				<mesh
					geometry={nodes.Cube001_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					geometry={nodes.Cube001_2.geometry}
					material={materials["Material.003"]}
				/>
			</group>
			<mesh
				geometry={nodes.Cube001.geometry}
				material={materials["Material.004"]}
				position={[-1.072, 1.869, -3.229]}
				rotation={[0, -1.57, 0]}
				scale={[0.769, 0.037, 2.195]}
			/>
			<mesh
				geometry={nodes.Cube008.geometry}
				material={materials["Material.009"]}
				position={[1.08, 0.982, -3.338]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-0.044, -0.897, -0.653]}
			/>
		</group>
	);
}

useGLTF.preload("Rooms/room.glb");
